swagger: "2.0"
info:
  version: 1.0.0
  title: Movies
host: moviestore.swagger.io
basePath: /test
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/info/:
    get:
      summary: Application info
      operationId: info
      responses:
        "200":
          description: Application info and request/context details
      x-amazon-apigateway-integration: ${api_integration}
  /v1/movies/:
    get:
      summary: List all movies
      operationId: listMovies
      tags:
        - movies
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of movies
          schema:
            $ref: '#/definitions/Movies'
      x-amazon-apigateway-integration: ${api_integration}
    post:
      summary: Create a movie
      operationId: createMovie
      tags:
        - movies
      responses:
        "201":
          description: The new movie
          schema:
            $ref: '#/definitions/Movie'
      x-amazon-apigateway-integration: ${api_integration}
  /v1/movies/{movieId}:
    get:
      summary: Details of a specific movie
      operationId: getMovieById
      tags:
        - movies
      parameters:
        - name: movieId
          in: path
          required: true
          description: The id of the movie to retrieve
          type: string
      responses:
        "200":
          description: Movie details
          schema:
            $ref: '#/definitions/Movie'
      x-amazon-apigateway-integration: ${api_integration}
    put:
      summary: Update movie details
      operationId: updateMovieById
      tags:
        - movies
      parameters:
        - name: movieId
          in: path
          required: true
          description: The id of the movie to update
          type: string
      responses:
        "200":
          description: The updated movie details
          schema:
            $ref: '#/definitions/Movie'
      x-amazon-apigateway-integration: ${api_integration}
    delete:
      summary: Delete movie
      operationId: deleteMovieById
      tags:
        - movies
      parameters:
        - name: movieId
          in: path
          required: true
          description: The id of the movie to delete
          type: string
      responses:
        "204":
          description: Empty respons
      x-amazon-apigateway-integration: ${api_integration}
definitions:
  Movie:
    properties:
      id:
        type: string
#        readOnly: true // not supported by API gateway
      title:
        type: string
      director:
        type: string
      year:
        type: integer
  Movies:
    type: array
    items:
      $ref: '#/definitions/Movie'
