AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Server-less demo application / movie database.

Resources:
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test

      DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location: swagger-sam.yaml

  APILambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/aws-serverless-movies-0.3.zip
      Handler: be.houbrechts.it.awsserverless.APILambda::handleRequest
      Runtime: java8
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DYNAMO_ENDPOINT_URL: http://dynamodb:8000
      Policies: AmazonDynamoDBFullAccess

  MovieTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: movies
      PrimaryKey:
         Name: id
         Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref APIGateway
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/test'

